"""Added puzzle_rating column with default value

Revision ID: 1b07f55a8118
Revises: 8142aa65c498
Create Date: 2025-03-13 19:54:53.039701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '1b07f55a8118'
down_revision = '8142aa65c498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzle_rating', sa.Integer(), nullable=True))  # Allow NULL initially
        batch_op.drop_constraint('user_puzzles_puzzle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'puzzles', ['puzzle_id'], ['id'])

    # Step 2: Populate puzzle_rating using puzzle_id
    conn = op.get_bind()
    conn.execute(text(
        "UPDATE user_puzzles SET puzzle_rating = (SELECT rating FROM puzzles WHERE puzzles.id = user_puzzles.puzzle_id)"
    ))

    # Step 3: Now enforce NOT NULL since all values are set
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.alter_column('puzzle_rating', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_puzzles_puzzle_id_fkey', 'puzzles', ['puzzle_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('puzzle_rating')

    # ### end Alembic commands ###
