"""added random col

Revision ID: 8142aa65c498
Revises: feb17083d14e
Create Date: 2025-03-13 15:37:13.903356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8142aa65c498'
down_revision = 'feb17083d14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user_puzzles', sa.Column('random', sa.Boolean(), server_default=sa.text('true'), nullable=False))

        # Now, remove the default to avoid unintended behavior in future inserts
        op.alter_column('user_puzzles', 'random', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.drop_column('random')

    # ### end Alembic commands ###
