"""Added hints_used field

Revision ID: feb17083d14e
Revises: 2a82e1a11804
Create Date: 2025-03-02 16:10:18.939334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb17083d14e'
down_revision = '2a82e1a11804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hints_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puzzles', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('hints_used')

    # ### end Alembic commands ###
